Refactor split between dui and install.
dui is now mostly about setup and download, while
install will do the actual installation from the unpacked
tarball.

diff --git a/sys/dui b/sys/dui
--- a/sys/dui
+++ b/sys/dui
@@ -1,54 +1,77 @@
 #! /bin/bash
 # DarqOS
-# Copyright (C) 2023 David Arnold
+# Copyright (C) 2023-2024 David Arnold
 
-
-# DarqOS Installer/Updater
+# DarqOS Updater/Installer
 
 # This script is used for either the initial install or subsequent
 # update of a DarqOS image on a Raspberry Pi OS machine.
 #
 # It will attempt to download the latest available image (or
 # optionally, a specified image) from the repository, unpack it,
-# configure the host OS as required, and copy over items from the
-# image to the host system as needed.
+# and launch the included install script.
 #
 # This whole process is kinda jank, but ... it's an easy way to start,
 # and can easily be refined later.  It cooperates with the `mkdist`
 # script that can be used to prepare images.
 
-DIST_FILE=darqos-latest.tar.gz
-DIST_BASE=https://www.0x1.org/d/darq
+# All events are logged to a file (for now), named with the datetime of
+# the install attempt.  This should be useful for debugging failed
+# executions.
 
+# Base variables.
 
-# Check /darq exists
-if [ ! -d /darq]; then
-    mkdir /darq
+if [ "x$DARQ" = x ]; then
+    DARQ=/darq
 fi
 
+if [ "x$DIST" = x ]; then
+    DIST=$DARQ/dist
+fi
 
-# Check raspi-config localisation defaults.
-# - Locale
-# - Timezone
-# - Keyboard layout
+if [ "x$DIST_FILE" = x ]; then
+    DIST_FILE=darqos-latest.tar.gz
+fi
 
-# Check raspi-config set for auto-login
+if [ "x$DIST_BASE" = x ]; then
+    DIST_BASE=https://www.0x1.org/d/darq
+fi
 
-# Check raspi-config SSH access is enabled (for now, at least).
+if [ "x$DARQ_USER" = x ]; then
+    DARQ_USER=darq
+fi
 
-# Check raspi-config WiFi location?
+# Check that we're running as root.
+if [ "`whoami`" != root ]; then
+    echo "Error: must run as root" >&2
+    exit 1
+fi
 
-# Check raspi-config "overscan" display setting.
+# Check or create darq user.
+if [ ! id $DARQ_USER >/dev/null 2>/dev/null ]; then
+    adduser darq
+fi
 
-# Update OS image.
-apt-get update
-apt-get -u dist-upgrade
-apt autoremove
+# Check $DARQ exists.
+if [ ! -d $DARQ ]; then
+    mkdir -p $DARQ
+    if [ ! -d $DARQ ]; then
+        echo "Error: unable to make $DARQ directory" >&2
+        exit 1
+    fi
+fi
 
-# Install X11 packages needed to run PyQt5 apps.
-apt-get install --no-install-recommends xserver-xorg x11-xserver-utils xinit
+# Remove old $DIST, if it exists.
+if [ -d $DIST ]; then
+    rm -rf $DIST
+fi
 
-# Fetch DarqOS tarball
+# Make new distribution directory.
+mkdir -p $DIST
+chown $DARQ_USER:$DARQ_USER $DIST
+cd $DIST
+
+# Fetch DarqOS tarball.
 rm -rf /tmp/$DIST_FILE
 (cd /tmp; wget $DIST_BASE/$DIST_FILE)
 if [ ! -f /tmp/$DIST_FILE ]; then
@@ -56,15 +79,24 @@ if [ ! -f /tmp/$DIST_FILE ]; then
     exit 1
 fi
 
-# Unpack tarball into /dist
-if [ ! -d /dist]; then
-    mkdir /dist
-fi
-
-cd /dist
+# Unpack distribution.
 tar xf /tmp/$DIST_FILE
 
-# Run install script from dist
-if [ -x /dist/install ]; then
-    /dist/install
+# Reset ownership.
+chown -R $DARQ_USER:$DARQ_USER $DARQ
+
+# Run install script from dist.
+if [ ! -f $DIST/darq/sys/install ]; then
+    echo "Error: install script $DIST/darq/sys/install does not exist" >&2
+    exit 1
 fi
+
+chmod +x $DIST/darq/sys/install
+$DIST/darq/sys/install
+
+# Remove distribution files
+rm -rf /tmp/$DIST_FILE
+rm -rf $DIST
+
+# Done.
+exit 0
diff --git a/sys/install b/sys/install
--- a/sys/install
+++ b/sys/install
@@ -1,47 +1,96 @@
 #! /bin/bash
 # DarqOS
-# Copyright (C) 2023 David Arnold
-
+# Copyright (C) 2023-2024 David Arnold
 
 # This script will install an unpacked DarqOS distribution, typically
-# in the /dist directory, into the system directory, typically /darq.
+# in the /darq/dist directory, into the system directory, typically /darq.
 #
 # In addition, it will
 # - install any required Linux (Debian) packages
 # - create or update any required Linux configuration files
 # - create or update systemd units for Darq services
+# - install all needed Python packages
 #
 # After successful completion, the target system will be ready to
 # start (or restart) the updated Darq system.
 
-# Check and save unpacked distribution location.
-
-# Check existence of /darq, and create it if required.
+# At this point, a new system version is available in /darq/dist.  We
+# need to copy its components into /darq proper, and restart anything
+# that needs to.
 
 # Shut down DarqOS
+# FIXME: what's actually needed here?
+# FIXME: use systemd target?
 
-# Update Linux OS
+# Check for raspi-conf utility.
+if [ ! -x /usr/bin/raspi-config ]; then
+    echo "Error: unable to find /usr/bin/raspi-config utility" >&2
+    exit 1
+fi
+
+# Check raspi-config localisation defaults.
+# - Locale
+sudo raspi-config nonint do_change_locale C.UTF-8
+
+# - Timezone
+sudo raspi-config nonint do_change_timezone Australia/Sydney
+
+# - Keyboard layout
+sudo raspi-config nonint do_configure_keyboard us
+
+# Check raspi-config set for auto-login
+# B1: console, login required
+# B2: console, login automatically
+# B3: GUI, login required
+# B4: GUI, login automatically
+sudo raspi-config nonint do_boot_behaviour B2
+
+# Disable splash screen on boot.
+sudo raspi-config nonint do_boot_splash 1
+
+# Disable screen blanking.
+sudo raspi-config nonint do_blanking 1
+
+# Check raspi-config SSH access is enabled (for now, at least).
+sudo raspi-config nonint do_ssh 0
+
+# Check raspi-config WiFi location?
+sudo raspi-config nonint do_wifi_country AU
+
+# Check raspi-config "overscan" display setting.
+sudo raspi-config nonint do_overscan_kms 1 0
+sudo raspi-config nonint do_overscan_kms 2 0
+
+# Enable Wayland
+sudo raspi-config nonint do_wayland W2
+
+# FIXME: network config is done via nmcli
+
+
+# Create darq:darq user and home directory.
+
+# Update OS.
+# NOTE: Assume we start from RasPiOS Lite image.
 apt-get update
-apt-get -u dist-upgrade
+apt-get -u -y dist-upgrade
 apt autoremove
 
 # Install any required Debian packages
 apt-get install \
-        foot \
-        python3.11 \
-        python3.11-venv \
-        qtwayland5 \
-        weston
+        foot \              # terminal emulator
+        pyqt5 \             # Qt5 for Python
+        python3.11-venv \   # Python venv support
+        qtwayland5 \        # Support for Qt5 on Wayland
+        wayfire             # Minimalist Wayland compositor
 
 # Create virtual environment if it doesn't exist
-if test ! -d /darq/env; then
+if [ ! -d /darq/env ]; then
     python3.11 -m venv env
 fi
 
 # Install or update Python modules
 . env/bin/activate
 pip install --upgrade \
-    PyQt5 \
     orjson \
     pillow \
     pyqtdarktheme \
@@ -50,6 +99,17 @@ pip install --upgrade \
 # Create or update configuration files
 
 # Install all Darq files (copy?  or rsync?)
+for f in LICENSE darq kernel lenses services sys tasks types; do
+    cp -pr $f /darq/
+    # FIXME: chown
+    # FIXME: chmod
+    # FIXME: use install instead of cp ?
+done
 
 # Restart DarqOS
-exec /darq/sys/init
+# FIXME: use systemd target?
+
+# FIXME: what needs to be restarted?
+# FIXME: OS? (in which case, don't worry about services)
+# FIXME: just services? (iterate over list, and restart them)
+
